import type { Metadata } from "next";
import { manrope, inter } from "../lib/fonts";
import "./globals.css";
import { ThemeProvider } from "../components/theme/theme-provider";
import { Toaster } from "sonner";
import AuthListener from '@/components/auth/auth-listener';
import { createSupabaseServerClient } from "@/lib/supabase/server";   


export const metadata: Metadata = {
  title: "FlowFolio App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createSupabaseServerClient();
  const { data: { session } } = await supabase.auth.getSession();
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${manrope.variable} ${inter.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthListener serverSession={null} />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
